# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-24 00:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBenchTest', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(db_index=True, db_tablespace=b'indexes', max_length=200)),
                ('userBenchTest', models.ForeignKey(db_tablespace=b'indexes', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PressionSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuePression', models.FloatField(db_index=True, db_tablespace=b'indexes')),
                ('date', models.DateTimeField(db_index=True, db_tablespace=b'indexes', default=datetime.datetime.now)),
                ('benchTest', models.ForeignKey(db_tablespace=b'indexes', on_delete=django.db.models.deletion.CASCADE, to='sbtmApp.BenchTest')),
            ],
        ),
        migrations.CreateModel(
            name='RpmSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueRPM', models.FloatField(db_index=True, db_tablespace=b'indexes')),
                ('date', models.DateTimeField(db_index=True, db_tablespace=b'indexes', default=datetime.datetime.now)),
                ('benchTest', models.ForeignKey(db_tablespace=b'indexes', on_delete=django.db.models.deletion.CASCADE, to='sbtmApp.BenchTest')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueTemperature', models.FloatField(db_index=True, db_tablespace=b'indexes')),
                ('date', models.DateTimeField(db_index=True, db_tablespace=b'indexes', default=datetime.datetime.now)),
                ('benchTest', models.ForeignKey(db_tablespace=b'indexes', on_delete=django.db.models.deletion.CASCADE, to='sbtmApp.BenchTest')),
            ],
        ),
    ]
