# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-24 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbtmApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturesensor',
            name='localSensor',
            field=models.IntegerField(db_index=True, db_tablespace=b'indexes', default=0),
        ),
    ]
