# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbtmApp', '0003_pressionsensor_localsensor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PressionSensor',
            new_name='PressureSensor',
        ),
    ]
