# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbtmApp', '0004_auto_20170627_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressuresensor',
            old_name='valuePression',
            new_name='valuePressure',
        ),
    ]
