# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 02:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbtmApp', '0005_auto_20170627_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueCharge', models.FloatField(db_index=True, db_tablespace=b'indexes')),
                ('date', models.DateTimeField(db_index=True, db_tablespace=b'indexes', default=datetime.datetime.now)),
                ('benchTest', models.ForeignKey(db_tablespace=b'indexes', on_delete=django.db.models.deletion.CASCADE, to='sbtmApp.BenchTest')),
            ],
        ),
    ]
